In [138]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.figure_factory as ff
import datetime as dt

**Data Investegation**

In [139]:
df = pd.read_csv('/content/train-data.csv')

In [140]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         6019 non-null   int64
 1   Name               6019 non-null   object
 2   Location           6019 non-null   object
 3   Year               6019 non-null   int64
 4   Kilometers_Driven  6019 non-null   int64
 5   Fuel_Type          6019 non-null   object
 6   Transmission       6019 non-null   object
 7   Owner_Type         6019 non-null   object
 8   Mileage            6017 non-null   object
 9   Engine             5983 non-null   object
 10  Power              5983 non-null   object
 11  Seats              5977 non-null   float64
 12  New_Price          824 non-null    object
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 658.5+ KB

In [142]:
df.describe()

        Unnamed: 0         Year  Kilometers_Driven        Seats        Price
count  6019.000000  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   3009.000000  2013.358199       5.873838e+04     5.278735     9.479468
std    1737.679967     3.269742       9.126884e+04     0.808840    11.187917
min       0.000000  1998.000000       1.710000e+02     0.000000     0.440000
25%    1504.500000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3009.000000  2014.000000       5.300000e+04     5.000000     5.640000
75%    4513.500000  2016.000000       7.300000e+04     5.000000     9.950000
max    6018.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [143]:
df.isna().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [144]:
df.nunique()

Unnamed: 0           6019
Name                 1876
Location               11
Year                   22
Kilometers_Driven    3093
Fuel_Type               5
Transmission            2
Owner_Type              4
Mileage               442
Engine                146
Power                 372
Seats                   9
New_Price             540
Price                1373
dtype: int64

In [145]:
df.describe(include='O')

,Name,Location,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,New_Price
count,6019,6019,6019,6019,6019,6017,5983,5983,824
unique,1876,11,5,2,4,442,146,372,540
top,Mahindra XUV500 W8 2WD,Mumbai,Diesel,Manual,First,18.9 kmpl,1197 CC,74 bhp,95.13 Lakh
freq,49,790,3205,4299,4929,172,606,235,6

In [146]:
df.dtypes[df.dtypes=='object']

Name            object
Location        object
Fuel_Type       object
Transmission    object
Owner_Type      object
Mileage         object
Engine          object
Power           object
New_Price       object
dtype: object

In [147]:
cat_cols = df.select_dtypes(include="O").iloc[:,1:5]
for i in cat_cols:
    print(df[i].value_counts())
    print('-----------------')

Mumbai        790
Hyderabad     742
Kochi         651
Coimbatore    636
Pune          622
Delhi         554
Kolkata       535
Chennai       494
Jaipur        413
Bangalore     358
Ahmedabad     224
Name: Location, dtype: int64
-----------------
Diesel      3205
Petrol      2746
CNG           56
LPG           10
Electric       2
Name: Fuel_Type, dtype: int64
-----------------
Manual       4299
Automatic    1720
Name: Transmission, dtype: int64
-----------------
First             4929
Second             968
Third              113
Fourth & Above       9
Name: Owner_Type, dtype: int64
-----------------

In [148]:
df.quantile(numeric_only=True ,q=[0.7, 0.8, 0.9, 0.95, 0.99, 1])

      Unnamed: 0    Year  Kilometers_Driven  Seats    Price
0.70     4212.60  2015.0            68390.0    5.0    8.446
0.80     4814.40  2016.0            79000.0    5.0   12.500
0.90     5416.20  2017.0            97000.0    7.0   22.500
0.95     5717.10  2018.0           120000.0    7.0   32.446
0.99     5957.82  2019.0           172829.0    8.0   56.000
1.00     6018.00  2019.0          6500000.0   10.0  160.000

Calculating specific quantiles (percentiles) for numeric columns in a DataFrame, including the 70th, 80th, 90th, 95th, 99th percentiles, and the maximum value (100th percentile).

**Data Cleaning**

In [149]:
df['Brand'] = df['Name'].str.split(' ').str[0]
df['Model'] = df['Name'].str.split(' ').str[1]

In [150]:
df.drop(columns={'Name'}, inplace=True)

In [151]:
df.nunique()

Unnamed: 0           6019
Location               11
Year                   22
Kilometers_Driven    3093
Fuel_Type               5
Transmission            2
Owner_Type              4
Mileage               442
Engine                146
Power                 372
Seats                   9
New_Price             540
Price                1373
Brand                  31
Model                 212
dtype: int64

In [152]:
df.drop("Brand",inplace=True,axis=1)
df.drop("Model",inplace=True,axis=1)

In [153]:
df.drop("Unnamed: 0", inplace=True, axis=1)

In [154]:
df.nunique()

Location               11
Year                   22
Kilometers_Driven    3093
Fuel_Type               5
Transmission            2
Owner_Type              4
Mileage               442
Engine                146
Power                 372
Seats                   9
New_Price             540
Price                1373
dtype: int64

In [155]:
df.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [156]:
df=df[df['Seats'] != 0]

In [157]:
df.Seats.value_counts().sort_values(ascending=False)

5.0     5014
7.0      674
8.0      134
4.0       99
6.0       31
2.0       16
10.0       5
9.0        3
Name: Seats, dtype: int64

In [158]:
df['Engine'] = df['Engine'].str.rstrip(' CC')
df['Power'] = df['Power'].str.rstrip(' bhp')
df['New_Price'] = df['New_Price'].str.rstrip(' Lakh')
df['New_Price'] = df['New_Price'].str.rstrip(' Cr')


Removing the specified units ('CC' from 'Engine', 'bhp' from 'Power', 'Lakh' from 'New_Price', and 'Cr' from 'New_Price') from the respective columns in a DataFrame.

In [159]:
#l = ['Mileage', 'Engine', 'Power']
df['Engine'] = df['Engine'].astype('float')
df['Power']=pd.to_numeric(df['Power'] , errors = 'coerce')

In [160]:
df.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998.0,58.16,5.0,NaN,1.75
1,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582.0,126.20,5.0,NaN,12.50
2,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199.0,88.70,5.0,8.61,4.50
3,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248.0,88.76,7.0,NaN,6.00
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968.0,140.80,5.0,NaN,17.74

In [161]:
def convert(x):
    if str(x).endswith("km/kg"):
        return float(x.split(' ')[0])*0.74
    elif str(x).endswith("kmpl"):
        return float(x.split(' ')[0])

This function converts fuel efficiency values from 'km/kg' to 'kmpl' by multiplying the numeric part by 0.74 and extracts the numeric value for 'kmpl' for other cases.

In [162]:
df['Mileage']=df['Mileage'].apply(convert)

In [163]:
df.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Mumbai,2010,72000,CNG,Manual,First,19.684,998.0,58.16,5.0,NaN,1.75
1,Pune,2015,41000,Diesel,Manual,First,19.670,1582.0,126.20,5.0,NaN,12.50
2,Chennai,2011,46000,Petrol,Manual,First,18.200,1199.0,88.70,5.0,8.61,4.50
3,Chennai,2012,87000,Diesel,Manual,First,20.770,1248.0,88.76,7.0,NaN,6.00
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.200,1968.0,140.80,5.0,NaN,17.74

In [164]:
df.corr(numeric_only=True)['Price'].sort_values(ascending=False)

Price                1.000000
Power                0.772566
Engine               0.658431
Year                 0.305399
Seats                0.053247
Kilometers_Driven   -0.011586
Mileage             -0.302692
Name: Price, dtype: float64

In [165]:
df.drop(df[df['Kilometers_Driven'] > 100000].index, axis = 0, inplace = True)
df.drop(df[df['Power'] > 480].index, axis = 0, inplace = True)
df.drop(df[df['Engine'] > 5000].index, axis = 0, inplace = True)

This code removes rows from a DataFrame where 'Kilometers_Driven' is over 100,000, 'Power' is greater than 480, and 'Engine' is greater than 5,000, in-place.

In [166]:
df['Location'].unique()

array(['Mumbai', 'Pune', 'Chennai', 'Coimbatore', 'Hyderabad', 'Jaipur',
       'Kochi', 'Kolkata', 'Delhi', 'Bangalore', 'Ahmedabad'],
      dtype=object)

In [167]:
df.Owner_Type = df.Owner_Type.map({'First':1, 'Second':2, 'Third':3, 'Fourth & Above':4})
df.Fuel_Type = df.Fuel_Type.map({'Diesel':1, 'Petrol':2, 'CNG':3})
df.Transmission = df.Transmission.map({'Manual':1, 'Automatic':2})
df.Location = df.Location.map({'Mumbai':1,'Pune':2, 'Chennai':3, 'Coimbatore':4, 'Hyderabad':5, 'Jaipur':6,
       'Kochi':7, 'Kolkata':8, 'Delhi':9, 'Bangalore':10, 'Ahmedabad':11})

df['Owner_Type'] = df['Owner_Type'].astype('float')
df['Fuel_Type'] = df['Fuel_Type'].astype('float')
df['Transmission'] = df['Transmission'].astype('float')
df['Location'] = df['Location'].astype('float')

This code maps and converts categorical columns 'Owner_Type,' 'Fuel_Type,' 'Transmission,' and 'Location' into numeric values and then changes their data types to float for numerical analysis.

In [168]:
df.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1.0,2010,72000,3.0,1.0,1.0,19.684,998.0,58.16,5.0,NaN,1.75
1,2.0,2015,41000,1.0,1.0,1.0,19.670,1582.0,126.20,5.0,NaN,12.50
2,3.0,2011,46000,2.0,1.0,1.0,18.200,1199.0,88.70,5.0,8.61,4.50
3,3.0,2012,87000,1.0,1.0,1.0,20.770,1248.0,88.76,7.0,NaN,6.00
4,4.0,2013,40670,1.0,2.0,2.0,15.200,1968.0,140.80,5.0,NaN,17.74

**Data Splitting**

In [169]:
df.isna().sum()

Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type              12
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 33
Power                 119
Seats                  38
New_Price            4713
Price                   0
dtype: int64

In [170]:
# Data Splitting

X = df[['Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats','New_Price']]
y = df[['Price']]

In [171]:
X

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,1.0,2010,72000,3.0,1.0,1.0,19.684,998.0,58.16,5.0,NaN
1,2.0,2015,41000,1.0,1.0,1.0,19.670,1582.0,126.20,5.0,NaN
2,3.0,2011,46000,2.0,1.0,1.0,18.200,1199.0,88.70,5.0,8.61
3,3.0,2012,87000,1.0,1.0,1.0,20.770,1248.0,88.76,7.0,NaN
4,4.0,2013,40670,1.0,2.0,2.0,15.200,1968.0,140.80,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6014,9.0,2014,27365,1.0,1.0,1.0,28.400,1248.0,74.00,5.0,7.88
6015,6.0,2015,100000,1.0,1.0,1.0,24.400,1120.0,71.00,5.0,NaN
6016,6.0,2012,55000,1.0,1.0,2.0,14.000,2498.0,112.00,8.0,NaN
6017,8.0,2013,46000,2.0,1.0,1.0,18.900,998.0,67.10,5.0,NaN
6018,5.0,2011,47000,1.0,1.0,1.0,25.440,936.0,57.60,5.0,NaN

In [172]:
X.shape

(5503, 11)

In [173]:
y.shape

(5503, 1)

In [174]:
y.isna().sum()

Price    0
dtype: int64

In [175]:

## We will use stratify because we have only 2 electric cars , so we don't want them to be both at the same split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #stratify=X['Fuel_Type'])

In [176]:
## We will impute null values using Simple imputer
null_cols = ['Engine','Mileage','Power','Seats','Fuel_Type','New_Price']

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
X_train[null_cols] = imputer.fit_transform(X_train[null_cols])
X_test[null_cols] = imputer.transform(X_test[null_cols])

In [177]:
X_test.isna().sum()

Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
dtype: int64

In [178]:
X_train.isna().sum()

Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
dtype: int64

**Model Building**

In [179]:
# Model Building
from sklearn.linear_model import LinearRegression

# Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)

# Model Evaluation
from sklearn.metrics import mean_squared_error, r2_score

# Predictions
y_pred = lr.predict(X_test)

# Model Evaluation
print('Training Score: ', lr.score(X_train, y_train))
print('Testing Score: ', lr.score(X_test, y_test))
print('RMSE: ', np.sqrt(mean_squared_error(y_test, lr.predict(X_test))))

Training Score:  0.7236887620427963
Testing Score:  0.7060001706800566
RMSE:  5.9756357797898145

In [180]:
prices = np.expm1(lr.predict(X_test))
prices

array([[1.75518746e+04],
       [6.54797697e+01],
       [6.55649619e+04],
       ...,
       [8.69691337e+02],
       [8.89647781e+01],
       [4.68764003e+02]])

In [181]:
# Random Forest Regressor

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=10, random_state=42, max_depth=10)

rf.fit(X_train, y_train)

print('Training Score: ', rf.score(X_train, y_train))
print('Testing Score: ', rf.score(X_test, y_test))
print('RMSE: ', np.sqrt(mean_squared_error(y_test, rf.predict(X_test))))

<ipython-input-181-b1e62c76bed4>:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)

Training Score:  0.9714598807493642
Testing Score:  0.797428550641839
RMSE:  4.960205819509037

This code trains a Random Forest Regressor model with 10 trees, evaluates its training and testing scores, and calculates the Root Mean Squared Error (RMSE) for the model's predictions on the test data.

In [182]:
# Decision Tree Regressor

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(max_depth=8, random_state=42)

dt.fit(X_train,y_train)

print('Training Score: ', dt.score(X_train, y_train))
print('Testing Score: ', dt.score(X_test, y_test))

Training Score:  0.9379183215585478
Testing Score:  0.665673036824594


This code trains a Decision Tree Regressor with a maximum depth of 8, evaluates its training and testing scores, which indicate its performance on the training and test data, respectively.

In [183]:
# Support Vector Regressor

from sklearn.svm import SVR

## Fitting the Data
svr = SVR()

svr.fit(X_train, y_train)

# Model Score

print('Training Score: ', svr.score(X_train, y_train))

print('Testing Score: ', svr.score(X_test, y_test))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Training Score:  -0.04568198714274563
Testing Score:  -0.028686550453228987

This code fits a Support Vector Regressor (SVR) model to the training data and prints its training and testing scores, which measure its performance on the respective datasets.

In [184]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor()
knn.fit(X_train, y_train)

print('Train Score : ' ,knn.score(X_train,y_train))

print('Test Score : ' ,knn.score(X_test, y_test))

Train Score :  0.708188198842771
Test Score :  0.6004167215203853

This code utilizes a K-Nearest Neighbors Regressor (KNN) to fit a model to the training data and then evaluates its performance on the training and test data by printing the training and testing scores, respectively.

In [185]:
models = [lr, rf, dt, svr , knn]
dic = {}
for model in models:
    model.fit(X_train, y_train)
    dic[model] =  model.score(X_test, y_test)

pd.DataFrame(dic, index=['Score']).T

<ipython-input-185-42b4574c2420>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

                                                       Score
LinearRegression()                                  0.706000
(DecisionTreeRegressor(max_depth=10, max_featur...  0.797429
DecisionTreeRegressor(max_depth=8, random_state...  0.665673
SVR()                                              -0.028687
KNeighborsRegressor()                               0.600417

This code fits all the machine learning models mentioned above to training data, calculates their testing scores, and creates a DataFrame displaying these scores for each model.

**Predicting Test Data**

In [186]:
df_test = pd.read_csv('/content/test-data.csv')
df_test.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN

In [187]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1234 non-null   int64
 1   Name               1234 non-null   object
 2   Location           1234 non-null   object
 3   Year               1234 non-null   int64
 4   Kilometers_Driven  1234 non-null   int64
 5   Fuel_Type          1234 non-null   object
 6   Transmission       1234 non-null   object
 7   Owner_Type         1234 non-null   object
 8   Mileage            1234 non-null   object
 9   Engine             1224 non-null   object
 10  Power              1224 non-null   object
 11  Seats              1223 non-null   float64
 12  New_Price          182 non-null    object
dtypes: float64(1), int64(3), object(9)
memory usage: 125.5+ KB

In [188]:
df_test.drop(columns={'Name'}, inplace=True)
df_test.drop("Unnamed: 0", inplace=True, axis=1)
df_test=df_test[df_test['Seats'] != 0]
df_test['Engine'] = df_test['Engine'].str.rstrip(' CC')
df_test['Power'] = df_test['Power'].str.rstrip(' bhp')
df_test['New_Price'] = df_test['New_Price'].str.rstrip(' Lakh')
df_test['New_Price'] = df_test['New_Price'].str.rstrip(' Cr')
df_test['Engine'] = df_test['Engine'].astype('float')
df_test['Power']=pd.to_numeric(df_test['Power'] , errors = 'coerce')
df_test['Mileage']=df_test['Mileage'].apply(convert)
df_test.drop(df_test[df_test['Kilometers_Driven'] > 100000].index, axis = 0, inplace = True)
df_test.drop(df_test[df_test['Power'] > 480].index, axis = 0, inplace = True)
df_test.drop(df_test[df_test['Engine'] > 5000].index, axis = 0, inplace = True)

df_test.Owner_Type = df_test.Owner_Type.map({'First':1, 'Second':2, 'Third':3, 'Fourth & Above':4})
df_test.Fuel_Type = df_test.Fuel_Type.map({'Diesel':1, 'Petrol':2, 'CNG':3})
df_test.Transmission = df_test.Transmission.map({'Manual':1, 'Automatic':2})
df_test.Location = df_test.Location.map({'Mumbai':1,'Pune':2, 'Chennai':3, 'Coimbatore':4, 'Hyderabad':5, 'Jaipur':6,
       'Kochi':7, 'Kolkata':8, 'Delhi':9, 'Bangalore':10, 'Ahmedabad':11})

df_test['Owner_Type'] = df_test['Owner_Type'].astype('float')
df_test['Fuel_Type'] = df_test['Fuel_Type'].astype('float')
df_test['Transmission'] = df_test['Transmission'].astype('float')
df_test['Location'] = df_test['Location'].astype('float')

In [189]:
df_test.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,9.0,2014,40929,3.0,1.0,1.0,23.8724,998.0,58.20,4.0,NaN
1,4.0,2013,54493,2.0,1.0,2.0,24.7000,796.0,47.30,5.0,NaN
2,1.0,2017,34000,1.0,1.0,1.0,13.6800,2393.0,147.80,7.0,25.27
4,1.0,2014,29000,2.0,1.0,1.0,18.5000,1197.0,82.85,5.0,NaN
5,4.0,2016,85609,1.0,1.0,2.0,16.0000,2179.0,140.00,7.0,NaN

In [190]:
df_test.isna().sum()

Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              2
Transmission           0
Owner_Type             0
Mileage                0
Engine                 8
Power                 24
Seats                  9
New_Price            941
dtype: int64

In [191]:
## We will impute null values using Simple imputer
null_cols = ['Engine','Power','Seats','Fuel_Type','New_Price']

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
df_test[null_cols] = imputer.fit_transform(df_test[null_cols])

In [192]:
df_test.isna().sum()

Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
dtype: int64

In [193]:

#df_test_preprocessed = preprocessor.transform(df_test)
log_price = model.predict(df_test) # in log scale
price = np.expm1(log_price) # in original scale

##Price Lakh
print('Price : ', price[0])

## Price In dollars
price_usd = price[0] * 1219
print('Price in USD:', price_usd)

Price :  [38.72576621]
Price in USD: [47206.70900559]

In [194]:
price

array([[3.87257662e+01],
       [3.70918367e+01],
       [2.42234036e+09],
       ...,
       [2.29747238e+03],
       [7.21125475e+01],
       [8.95748352e+06]])

In [195]:
df_test['price'] = price.tolist()

In [196]:
df_test

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,price
0,9.0,2014,40929,3.0,1.0,1.0,23.8724,998.0,58.20,4.0,18.024886,[38.725766206394184]
1,4.0,2013,54493,2.0,1.0,2.0,24.7000,796.0,47.30,5.0,18.024886,[37.091836725399006]
2,1.0,2017,34000,1.0,1.0,1.0,13.6800,2393.0,147.80,7.0,25.270000,[2422340357.321406]
4,1.0,2014,29000,2.0,1.0,1.0,18.5000,1197.0,82.85,5.0,18.024886,[26.112638920657883]
5,4.0,2016,85609,1.0,1.0,2.0,16.0000,2179.0,140.00,7.0,18.024886,[4349.299620558328]
...,...,...,...,...,...,...,...,...,...,...,...,...
1229,5.0,2011,89411,1.0,1.0,1.0,20.5400,1598.0,103.60,5.0,18.024886,[45.61861850168266]
1230,1.0,2015,59000,2.0,2.0,1.0,17.2100,1197.0,103.60,5.0,18.024886,[55.826342805469025]
1231,8.0,2012,28000,1.0,1.0,1.0,23.0800,1461.0,63.10,5.0,18.024886,[2297.472383122332]
1232,2.0,2013,52262,2.0,2.0,3.0,17.2000,1197.0,103.60,5.0,18.024886,[72.11254746690634]
1233,7.0,2014,72443,1.0,2.0,1.0,10.0000,2148.0,170.00,5.0,18.024886,[8957483.520009007]

In [197]:
import numpy as np
import pandas as pd

# Assuming df_test is a pandas DataFrame with a column New_Price
# Ensure that df_test.New_Price is a pandas Series with numerical values

# Example data cleaning steps (modify as needed):
# Check data type
if not isinstance(df_test.New_Price, (pd.Series, np.ndarray)):
    df_test['New_Price'] = pd.to_numeric(df_test['New_Price'], errors='coerce')

# Ensure numerical values
df_test['New_Price'] = pd.to_numeric(df_test['New_Price'], errors='coerce')

# Handle missing or invalid values (e.g., fill missing values with 0)
df_test['New_Price'].fillna(0, inplace=True)

# Now you can use np.log1p on df_test.New_Price
target = np.log1p(df_test.New_Price)

This code prepares the 'New_Price' column in the DataFrame 'df_test' by ensuring it contains numerical values, handling missing or invalid values by filling them with 0, and then applying the natural logarithm transformation (np.log1p) to the 'New_Price' values, typically for modeling purposes.

In [198]:
target = np.log1p(df_test.New_Price)

In [199]:
df_test.drop("Location",inplace=True,axis=1)

In [200]:
df_test

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,price
0,2014,40929,3.0,1.0,1.0,23.8724,998.0,58.20,4.0,18.024886,[38.725766206394184]
1,2013,54493,2.0,1.0,2.0,24.7000,796.0,47.30,5.0,18.024886,[37.091836725399006]
2,2017,34000,1.0,1.0,1.0,13.6800,2393.0,147.80,7.0,25.270000,[2422340357.321406]
4,2014,29000,2.0,1.0,1.0,18.5000,1197.0,82.85,5.0,18.024886,[26.112638920657883]
5,2016,85609,1.0,1.0,2.0,16.0000,2179.0,140.00,7.0,18.024886,[4349.299620558328]
...,...,...,...,...,...,...,...,...,...,...,...
1229,2011,89411,1.0,1.0,1.0,20.5400,1598.0,103.60,5.0,18.024886,[45.61861850168266]
1230,2015,59000,2.0,2.0,1.0,17.2100,1197.0,103.60,5.0,18.024886,[55.826342805469025]
1231,2012,28000,1.0,1.0,1.0,23.0800,1461.0,63.10,5.0,18.024886,[2297.472383122332]
1232,2013,52262,2.0,2.0,3.0,17.2000,1197.0,103.60,5.0,18.024886,[72.11254746690634]
1233,2014,72443,1.0,2.0,1.0,10.0000,2148.0,170.00,5.0,18.024886,[8957483.520009007]